TouchMeNot/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('virtualscreen.urls')),
    path('accounts/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

urlpatterns = [
    path('signout/', LogoutView.as_view(template_name='users/sign-out.html'), name='sign-out'),
    path('sign-up/', views.register, name='sign-up'),
    path('sign-in/', LoginView.as_view(template_name='users/sign-in.html'), name='sign-in'),
    path('profile/', views.profile, name='profile'),
    path('post/<int:pk>/delete/', views.post_delete, name='post-delete'),
    # path('user-posts/<str:username>', views.UserPostListView.as_view(), name='user-posts'),
    path('create-post', views.create_post, name='create-post')
]

users/models.py
from django.db import models
from PIL import Image
from django.contrib.auth.models import User
from django.urls import reverse

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default_avatar.png', upload_to='profile_pics/')

    def __str__(self) -> str:
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)

        image = Image.open(self.image.path)
        if image.height > 300 or image.width > 300:
            output_size = (300, 300)
            image.thumbnail(output_size)
            image.save(self.image.path)


class Post(models.Model):
	description = models.CharField(max_length=255, blank=True)
	pic = models.ImageField(upload_to='doodle/')
	user_name = models.ForeignKey(User, on_delete=models.CASCADE)

	def __str__(self):
		return self.description


	def get_absolute_url(self):
		return reverse('profile', kwargs={'pk': self.pk})

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile
from .models import Post
from crispy_forms.helper import FormHelper


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']


class NewPostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ['description', 'pic']

	def __init__(self, *args, **kwargs):
		super(NewPostForm, self).__init__(*args, **kwargs)
        # If you pass FormHelper constructor a form instance
        # It builds a default layout with all its fields
		self.helper = FormHelper()

users/views.py
from django.shortcuts import redirect, render
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from .models import Post

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(
                request, 'Your account has been created! You are now able to log in.')
            return redirect('sign-in')
    else:
        form = UserRegisterForm()
    return render(request, 'users/sign-up.html', {'form': form})


@login_required
def post_delete(request, pk):
    post = Post.objects.get(pk=pk)
    if request.user == post.user_name:
        Post.objects.get(pk=pk).delete()
    return redirect('profile')


@login_required
def profile(request):
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileUpdateForm(
            request.POST, request.FILES, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            profile_form.save()
            user_form.save()
            messages.success(request, 'Your account has been updated!')
            return redirect('profile')
        else:
            return redirect('profile')
    else:
        user = request.user
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.profile)
        user_posts = Post.objects.filter(user_name=user)
    return render(request, 'users/profile.html', {'p_form': profile_form, 'u_form': user_form, 'post_count': user_posts.count, 'posts': user_posts})


@login_required
def create_post(request):
    user = request.user
    if request.method == "POST":
        description = request.POST.get('description')
        image = request.POST.get('image')
        image = '/doodle/' + image
        user.post_set.create(description=description, pic=image)
        messages.success(request, 'Image saved successfully!')
        return redirect('profile')
    return render(request, 'users/profile.html')

templates/users/base.html
<!DOCTYPE html>
<html>
{% load static %}
<head>

   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width">
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
  
    <link href="{% static 'assets/css/main.css' %}" rel="stylesheet">
    <!-- Google Fonts -->
    <link
        href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet">


    {% if title %}
        <title>TouchMeNot - {{ title }}</title>
    {% else %}
        <title>TouchMeNot</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href='/'>TouchMeNot</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            {% if user.is_authenticated %}
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="/">Home</a>
              <a class="nav-item nav-link" href="{% url 'contact' %}">Contact</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
              <a class="nav-item nav-link" href="{% url 'sign-out' %}">Sign Out</a>
            </div>
            {% else %}
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="/">Home</a>
              <a class="nav-item nav-link" href="{% url 'contact' %}">Contact</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              <a class="nav-item nav-link" href="{% url 'sign-in' %}">Sign In</a>
              <a class="nav-item nav-link" href="{% url 'sign-up' %}">Sign Up</a>
            </div>
            {% endif %}
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-12">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
      crossorigin="anonymous"></script>
</body>
</html>

templates/users/forgotpassword.html
<!DOCTYPE html>
<body>
<div id="highlighted" class="hl-basic hidden-xs">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-9 col-sm-offset-3 col-md-9 col-md-offset-3 col-lg-10 col-lg-offset-2">
        <h1>Forgot Password</h1>
      </div>
    </div>
  </div>
</div>
<div id="content" class="interior-page">
  <div class="container-fluid">
    <div class="row">
    
      <!--Sidebar-->
      <div class="col-sm-3 col-md-3 col-lg-2 sidebar equal-height interior-page-nav hidden-xs">
        <div class="dynamicDiv panel-group" id="dd.0.1.0">
          <div id="subMenu" class="panel panel-default">
            <ul class="subMenuHighlight panel-heading">
              <li class="subMenuHighlight panel-title" id="subMenuHighlight">
                <a id="li_291" class="subMenuHighlight" href=""><span>Register</span></a>
              </li>
            </ul>
            <ul class="panel-heading">
              <li class="panel-title">
                <a class="subMenu1" href=""><span class="subMenuHighlight">Forgot Password</span></a>
              </li>
            </ul>
            <ul class="panel-heading">
              <li class="panel-title">
                <a class="subMenu1" href=""><span>Login</span></a>
              </li>
            </ul>
          </div>
          <div class="item item-nopad item-noborder item-gold">
            <a style="padding: 5% 0px;" href="" class="btn btn-primary btn-block" role="button">LEARN MORE</a> 
          </div>
        </div>
      </div>

      <!--Content-->
      <div class="col-sm-9 col-md-9 col-lg-10 content equal-height">
        <div class="content-area-right">
          <div class="content-crumb-div">
            <a href="">Home</a> | <a href="">Your Account</a> | Forgot Password
          </div>
          <div class="row">
            <div class="col-md-5 forgot-form">
              <p>Please enter your email address below and we will send you information to change your password.</p>
              <label class="label-default" for="un">Email Address</label> <input id="email_addy" name="email_addy" class="form-control" type="text"><br>
              <a id="mybad" class="btn btn-primary" role="button">I FORGOT</a>
            </div>
            <div class="col-md-5 forgot-return" style="display:none;">
              <h2>Reset Password Sent</h2>
              <p>An email has been sent to your address with a reset password you can use to access your account.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</body>

templates/users/profile.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="content-section">
    <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
        <div class="media-body">
            <h2 class="account-heading">{{ user.username }}</h2>
            <p class="text-secondary">{{ user.email }}</p>
        </div>
    </div>

    <form method="POST" id='pro' class="form-control" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Profile Info</legend>
            {{ u_form|crispy}}
            {{ p_form|crispy }}
        </fieldset>
        <div class="form-group">
            <button type="submit" class="btn btn-outline-info">Update</button>
        </div>
    </form>
</div>
<div class='content-section'>
    <h2 class="account-heading">Doodle</h2>
    <legend class="border-bottom mb-4">Doodle Gallery</legend>
    <div class="row">
        <div class="col-lg-6">
            {% for post in posts %}
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-4">
                        <a href="{{ post.pic.url }}"><img src="{{ post.pic.url }}" class="img-fluid rounded-start" alt="..."></a>
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <p class="card-text mt-5">{{ post.description }}</p>
                        </div>
                    </div>
                    <a
                    class="btn btn-outline-danger"
                    href="{% url 'post-delete' post.id %}"
                    >Delete</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <legend class="border-bottom mb-4">Upload Doodle</legend>
    <form method="POST" action={% url 'create-post' %} class="form-control">
        {% csrf_token %}
        <fieldset class="form-group">
            <div id="div_id_username" class="control-group"> <label for="id_username" class="control-label requiredField">
                    Doodle description<span class="asteriskField">*</span> </label>
                <div class="controls"> <input type="text" name="description" maxlength="50"
                        class="textinput textInput" required="" id="id_username">
                    <p id="hint_id_username" class="help-block">Required. 50 characters or fewer. Letters, digits and
                        @/./+/-/_ only.</p>
                </div>
            </div>
            <div id="div_id_image" class="control-group"> <label for="id_image" class="control-label requiredField">
                    Doodle Image<span class="asteriskField">*</span> </label>
                <div class="controls">
                    Change:
                    <input type="file" name="image" accept="image/*" class="clearablefileinput" id="id_image">
                </div>
            </div>
        </fieldset>
        <div class="form-group">
            <button type="submit" name="doodle" class="btn btn-outline-info">Create Doodle</button>
        </div>
    </form>
    
</div>
{% endblock content %}

templates/users/sign-in.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group mt-3">
                <button type="submit" class="btn btn-outline-info">Login</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need an account? <a class="ml-2" href="{% url 'sign-up' %}">Sign Up Now</a>
            </small>
        </div>
    </div>
{% endblock content %}

templates/users/sign-out.html
{% extends 'users/base.html' %}
{% block content %}
    <h2>You have been logged out</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'sign-in' %}">Log In Again</a>
        </small>
    </div>
{% endblock content %}

templates/users/sign-up.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}


{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button type="submit" class="btn btn-outline-info">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already have an account? <a class="ml-2" href="{% url 'sign-in' %}">Sign In</a>
            </small>
        </div>
    </div>

{% endblock content %}